// tests/scenarios/ellipsis.js
// 省略号/无语规则测试用例
// 挂载 window.__TestScenarios_ellipsis

window.__TestScenarios_ellipsis = [
    { name: '省略号 · 两人相对无言（有冒号）',
        mode: 'eliza',
      input: '张三: ...\n李四: ...',
      check: function(items) { return items.some(function(i) { return /无言|省略号|沉默|相对/.test(i.text||''); }); } },
    { name: '省略号 · 两人相对无言（无冒号格式）',
        mode: 'eliza',
      input: '张三...\n李四...',
      check: function(items) { return items.some(function(i) { return /无言|省略号|沉默|相对/.test(i.text||''); }); } },
    { name: '省略号 · 六句号无语',
        mode: 'eliza',
      input: '王五: ......',
      check: function(items) { return items.some(function(i) { return /无语|句号|空白|沉默/.test(i.text||''); }); } },
    { name: '省略号 · 中文句号无语',
        mode: 'eliza',
      input: '赵六: 。。。。。。',
      check: function(items) { return items.some(function(i) { return /无语|句号/.test(i.text||''); }); } },
    { name: '省略号 · 沉默后开口',
        mode: 'eliza',
      input: '...\n他说：我知道了。',
      check: function(items) { return items.some(function(i) { return /沉默|开口|打破|找回/.test(i.text||''); }); } },
    { name: '省略号 · 说完只剩省略号',
        mode: 'eliza',
      input: '她说了很多，最后停了下来。\n...',
      check: function(items) { return items.some(function(i) { return /省略号|话已|说尽|戛然而止|黑暗/.test(i.text||''); }); } },
    { name: '省略号 · 纯省略号对话',
        mode: 'eliza',
      input: '...\n...',
      check: function(items) { return items.some(function(i) { return /省略号|说不出口|无言|频道|噪音/.test(i.text||''); }); } },
    { name: '省略号 · 克苏鲁语境',
        mode: 'eliza',
      input: '调查员A: ...\n调查员B: ...\n古神的低语在他们脑海中回荡。',
      check: function(items) { return items.some(function(i) { return /古神|疯狂|低语|失语/.test(i.text||''); }); } },
    { name: '省略号 · 赛博朋克语境',
        mode: 'eliza',
      input: '操作员A: ...\n操作员B: ...\n数据流中断，AI系统离线。',
      check: function(items) { return items.some(function(i) { return /白噪音|信号|频道|通讯/.test(i.text||''); }); } },
    { name: '省略号 · 正常说话防护',
        mode: 'eliza',
      input: '张三: ......\n李四说道："这件事我知道。"',
      check: function(items) { return !items.some(function(i) { return /彻底无语|句号无语/.test(i.text||''); }); } }
];