// tests/scenarios/pool.js
// 变体池测试用例
// 挂载 window.__TestScenarios_pool

window.__TestScenarios_pool = [
    { name: '变体池 · 眼泪规则有产出',
        mode: 'eliza',
      input: '她的眼泪夺眶而出，顺着脸颊滑落。',
      check: function(items) { return items.some(function(i) { return /泪/.test(i.text||'') && (i.text||'').length > 3; }); } },
    { name: '变体池 · 同一规则两次触发不重复',
        mode: 'eliza',
      input: '她泪流满面。他也泪流满面。',
      check: function(items) { var t = items.filter(function(i) { return /泪/.test(i.text||''); }); return t.length >= 2 && t[0].text !== t[1].text; } },
    { name: '变体池 · 拔剑规则（长剑出鞘）',
        mode: 'eliza',
      input: '他抽出腰间的长剑，寒光一闪。',
      check: function(items) { return items.some(function(i) { return /出鞘|寒光|锋芒|凝滞/.test(i.text||''); }); } },
    { name: '变体池 · 拔刀规则',
        mode: 'eliza',
      input: '她拔出腰间的弯刀，刀锋映着月光。',
      check: function(items) { return items.some(function(i) { return /出鞘|刀锋|一闪/.test(i.text||''); }); } },
    { name: '变体池 · 重兵出阵',
        mode: 'eliza',
      input: '他抡起铁锤砸向地面。',
      check: function(items) { return items.some(function(i) { return /重兵|破空|战器/.test(i.text||''); }); } },
    { name: '变体池 · 端起弓弩',
        mode: 'eliza',
      input: '她端起弓，瞄准了远处的目标。',
      check: function(items) { return items.some(function(i) { return /兵器|武器|定格|蓄势/.test(i.text||''); }); } },
    { name: '变体池 · 女子入场',
        mode: 'eliza',
      input: '一位白衣女子走进大殿。',
      check: function(items) { return items.some(function(i) { return /女子|步入|刹那/.test(i.text||''); }); } },
    { name: '变体池 · 难以置信',
        mode: 'eliza',
      input: '他简直不敢相信自己的眼睛。',
      check: function(items) { return items.some(function(i) { return /难以置信|震惊|静止/.test(i.text||''); }); } },
    { name: '变体池 · 声音消失',
        mode: 'eliza',
      input: '所有声音瞬间消失了。',
      check: function(items) { return items.some(function(i) { return /声音消失|静音|涌来/.test(i.text||''); }); } },
    { name: '变体池 · 风尘仆仆',
        mode: 'eliza',
      input: '一个风尘仆仆的行者走进客栈。',
      check: function(items) { return items.some(function(i) { return /风尘|身影|来者/.test(i.text||''); }); } },
    { name: '变体池 · 对峙（扩展池）',
        mode: 'eliza',
      input: '两人僵持着，谁也不肯退让。',
      check: function(items) { return items.some(function(i) { return /对峙|僵持|退让|冲突|凝固/.test(i.text||''); }); } },
    { name: '变体池 · 顿悟（扩展）',
        mode: 'eliza',
      input: '他幡然醒悟，原来一切早已注定。',
      check: function(items) { return items.some(function(i) { return /顿悟|豁然|醒|刹那/.test(i.text||''); }); } },
    { name: '变体池 · 高燃时刻',
        mode: 'eliza',
      input: '那一刻，全场燃炸了。',
      check: function(items) { return items.some(function(i) { return /高燃|逆光|剪影/.test(i.text||''); }); } },
    { name: '变体池 · 江山社稷',
        mode: 'eliza',
      input: '他肩负着天下苍生的命运。',
      check: function(items) { return items.some(function(i) { return /天下|苍生|重担/.test(i.text||''); }); } },
    { name: '变体池 · 末日降临',
        mode: 'eliza',
      input: '天灾降临，大地崩裂。',
      check: function(items) { return items.some(function(i) { return /末日|景象/.test(i.text||''); }); } },
    { name: '变体池 · 风中场景',
        mode: 'eliza',
      input: '凛冽的寒风吹过荒原。',
      check: function(items) { return items.some(function(i) { return /风中|风/.test(i.text||''); }); } },
    { name: '变体池 · 雾中场景',
        mode: 'eliza',
      input: '浓重的雾气笼罩着山谷。',
      check: function(items) { return items.some(function(i) { return /雾中|雾/.test(i.text||''); }); } }
];